TRAIN_VOCAB_EN: data/train_vocab_en.txt
TRAIN_VOCAB_TR: data/train_vocab_tr.txt
RESULT_DIR: results/
LOG_DIR: logs/
CHK_DIR: checkpoints/
DATA_DIR: /home/ubuntu/workspace/221122_vmt_hyunbin/VRET/data/
MAX_INPUT_LENGTH: 40
MAX_VID_LENGTH: 32
batch_size: 64
epochs: 1 #100
seed: 1917
model_type: s2s
#train_id: tr2en_vid_self_attn_co_gate
train_id: rhye
#train_id: en2tr_vid_ffn
nb_blocks: 6
d_model: 512
att_h: 8
dropout: 0.5
maxlen: 35
warmup_steps: 9600
GCN_layer: 3
#GCN_layer: 1
lr: 0.0001
smoothing: 0.3